name: build and deploy chess app
on: [push]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands 
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /var/www/${{ secrets.USERNAME }}/chess

            git pull 

            npm ci 
            npm run build

            echo ${{ secrets.PASSWORD }} | sudo -S systemctl stop chess.service 
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl start chess.service 
            echo ${{ secrets.PASSWORD }} | sudo -S systemctl reload nginx
